const bancoPreguntas = {
  "Matemáticas":[
    {pregunta:"8 × 7 =", opciones:["54","56","49","64"], correcta:1},
    {pregunta:"Triángulo con 3 lados iguales", opciones:["Escaleno","Isósceles","Equilátero","Rectángulo"], correcta:2},
    {pregunta:"Valor aproximado de π", opciones:["3.14","3.45","2.17","4.13"], correcta:0},
    {pregunta:"Raíz cuadrada de 81", opciones:["8","9","7","10"], correcta:1},
    {pregunta:"Inversa de multiplicación", opciones:["División","Suma","Resta","Potenciación"], correcta:0},
    {pregunta:"5 + 12 =", opciones:["16","17","18","19"], correcta:1},
    {pregunta:"12 ÷ 3 =", opciones:["4","3","5","6"], correcta:0},
    {pregunta:"7² =", opciones:["49","14","21","28"], correcta:0},
    {pregunta:"Número primo", opciones:["4","6","7","9"], correcta:2},
    {pregunta:"50% de 200", opciones:["50","100","150","200"], correcta:1},
    {pregunta:"Fracción equivalente a 1/2", opciones:["2/4","3/5","1/3","2/5"], correcta:0},
    {pregunta:"9 × 6 =", opciones:["54","45","56","63"], correcta:0},
    {pregunta:"Número par", opciones:["7","9","12","13"], correcta:2},
    {pregunta:"15 + 27 =", opciones:["42","41","43","40"], correcta:0},
    {pregunta:"10² =", opciones:["100","10","20","50"], correcta:0}
  ],

  "Historia":[
    {pregunta:"Revolución Francesa", opciones:["1789","1810","1776","1492"], correcta:0},
    {pregunta:"Quién descubrió América", opciones:["Colón","Bolívar","Napoleón","Marco Polo"], correcta:0},
    {pregunta:"Continente Imperio Romano", opciones:["Asia","Europa","África","América"], correcta:1},
    {pregunta:"Primer presidente EEUU", opciones:["Washington","Lincoln","Jefferson","Adams"], correcta:0},
    {pregunta:"Civilización pirámides", opciones:["Mayas","Egipcios","Incas","Griegos"], correcta:1},
    {pregunta:"Edad Media comenzó en", opciones:["476","1492","1789","1066"], correcta:0},
    {pregunta:"La Ilustración fue en", opciones:["Siglo XVIII","Siglo XVII","Siglo XIX","Siglo XVI"], correcta:0},
    {pregunta:"Primera Guerra Mundial", opciones:["1914","1939","1812","1945"], correcta:0},
    {pregunta:"Revolución Industrial", opciones:["Siglo XVIII","Siglo XIX","Siglo XVII","Siglo XX"], correcta:0},
    {pregunta:"Muro de Berlín cayó en", opciones:["1989","1991","1979","1961"], correcta:0},
    {pregunta:"Napoleón nació en", opciones:["Francia","Italia","España","Alemania"], correcta:1},
    {pregunta:"Rey Sol de Francia", opciones:["Luis XIV","Carlos III","Luis XVI","Enrique IV"], correcta:0},
    {pregunta:"Revolución Rusa", opciones:["1917","1905","1920","1914"], correcta:0},
    {pregunta:"Imperio Bizantino cayó en", opciones:["1453","1492","1300","1600"], correcta:0},
    {pregunta:"Primer hombre en la luna", opciones:["Neil Armstrong","Buzz Aldrin","Yuri Gagarin","John Glenn"], correcta:0}
  ],

  "Biología":[
    {pregunta:"Unidad básica de la vida", opciones:["Molécula","Célula","Átomo","Tejido"], correcta:1},
    {pregunta:"Gas fotosíntesis", opciones:["Oxígeno","CO2","Nitrógeno","Helio"], correcta:1},
    {pregunta:"Proceso respiración", opciones:["Fotosíntesis","Digestión","Respiración","Circulación"], correcta:2},
    {pregunta:"Órgano bombea sangre", opciones:["Pulmones","Hígado","Corazón","Cerebro"], correcta:2},
    {pregunta:"Hueso más largo", opciones:["Fémur","Radio","Tibia","Húmero"], correcta:0},
    {pregunta:"Sistema digestivo inicia en", opciones:["Boca","Estómago","Intestino","Hígado"], correcta:0},
    {pregunta:"Células rojas transportan", opciones:["O2","CO2","Nutrientes","Hormonas"], correcta:0},
    {pregunta:"Plantas realizan fotosíntesis en", opciones:["Raíces","Hojas","Tallos","Flores"], correcta:1},
    {pregunta:"Ser vivo unicelular", opciones:["Bacteria","Humano","Perro","Árbol"], correcta:0},
    {pregunta:"Esqueleto protege", opciones:["Órganos","Sangre","Músculos","Piel"], correcta:0},
    {pregunta:"Reproducción sexual implica", opciones:["2 gametos","1 célula","3 gametos","4 células"], correcta:0},
    {pregunta:"ADN se encuentra en", opciones:["Núcleo","Citoplasma","Membrana","Mitocondria"], correcta:0},
    {pregunta:"Animal mamífero ovíparo", opciones:["Ornitorrinco","Perro","Gato","Conejo"], correcta:0},
    {pregunta:"Fotosíntesis produce", opciones:["Glucosa","Proteína","Lípidos","Ácido"], correcta:0},
    {pregunta:"Células nerviosas son", opciones:["Neuronas","Glóbulos","Hepatocitos","Osteocitos"], correcta:0}
  ],

  "Inglés":[
    {pregunta:"Hello significa", opciones:["Hola","Adiós","Gracias","Perro"], correcta:0},
    {pregunta:"Cat significa", opciones:["Gato","Perro","Pájaro","Ratón"], correcta:0},
    {pregunta:"How are you?", opciones:["¿Cómo estás?","¿Qué hora es?","¿Dónde vas?","¿Qué comes?"], correcta:0},
    {pregunta:"Thank you significa", opciones:["Gracias","Hola","Por favor","Bienvenido"], correcta:0},
    {pregunta:"Good morning significa", opciones:["Buenos días","Buenas noches","Buenas tardes","Hasta luego"], correcta:0},
    {pregunta:"Dog significa", opciones:["Perro","Gato","Conejo","Pájaro"], correcta:0},
    {pregunta:"Red significa", opciones:["Rojo","Verde","Azul","Amarillo"], correcta:0},
    {pregunta:"Book significa", opciones:["Libro","Mesa","Silla","Cuaderno"], correcta:0},
    {pregunta:"Water significa", opciones:["Agua","Fuego","Tierra","Aire"], correcta:0},
    {pregunta:"Mother significa", opciones:["Madre","Padre","Hermana","Hermano"], correcta:0},
    {pregunta:"Father significa", opciones:["Padre","Madre","Tío","Primo"], correcta:0},
    {pregunta:"Food significa", opciones:["Comida","Bebida","Fruta","Carne"], correcta:0},
    {pregunta:"School significa", opciones:["Escuela","Casa","Parque","Iglesia"], correcta:0},
    {pregunta:"Sleep significa", opciones:["Dormir","Correr","Comer","Beber"], correcta:0},
    {pregunta:"Car significa", opciones:["Coche","Bicicleta","Avión","Barco"], correcta:0}
  ],

  "Física":[
    {pregunta:"Fuerza se mide en", opciones:["Newton","Pascal","Joule","Watt"], correcta:0},
    {pregunta:"Velocidad = distancia / ?", opciones:["Tiempo","Masa","Fuerza","Área"], correcta:0},
    {pregunta:"Gravedad en la Tierra", opciones:["9.8 m/s²","10 m/s²","8.9 m/s²","12 m/s²"], correcta:0},
    {pregunta:"Unidad de energía", opciones:["Joule","Newton","Voltio","Amperio"], correcta:0},
    {pregunta:"Luz viaja más rápido que", opciones:["Sonido","Agua","Tierra","Fuego"], correcta:0},
    {pregunta:"Masa se mide en", opciones:["Kg","m","s","N"], correcta:0},
    {pregunta:"Aceleración = cambio de", opciones:["Velocidad","Tiempo","Fuerza","Distancia"], correcta:0},
    {pregunta:"Ley de Newton 2", opciones:["F=ma","E=mc²","V=d/t","p=mv"], correcta:0},
    {pregunta:"Unidad de presión", opciones:["Pascal","Newton","Joule","Watt"], correcta:0},
    {pregunta:"Electricidad se mide en", opciones:["Voltio","Newton","Joule","Watt"], correcta:0},
    {pregunta:"Ondas son", opciones:["Mecánicas","Químicas","Biológicas","Económicas"], correcta:0},
    {pregunta:"Magnetismo proviene de", opciones:["Imanes","Electricidad","Luz","Sonido"], correcta:0},
    {pregunta:"Velocidad de caída libre", opciones:["9.8 m/s²","10 m/s²","8 m/s²","12 m/s²"], correcta:0},
    {pregunta:"Trabajo = fuerza × ?", opciones:["Distancia","Masa","Velocidad","Tiempo"], correcta:0},
    {pregunta:"Potencia = trabajo / ?", opciones:["Tiempo","Masa","Fuerza","Velocidad"], correcta:0}
  ],
  "Química":[
  {pregunta:"Símbolo del agua", opciones:["H2O","O2","CO2","NaCl"], correcta:0},
  {pregunta:"Átomo más ligero", opciones:["Hidrógeno","Helio","Carbono","Oxígeno"], correcta:0},
  {pregunta:"pH neutro", opciones:["7","0","14","1"], correcta:0},
  {pregunta:"Elemento número 6", opciones:["Carbono","Oxígeno","Nitrógeno","Hidrógeno"], correcta:0},
  {pregunta:"Molécula orgánica básica", opciones:["Glucosa","Oxígeno","Sodio","Cloro"], correcta:0},
  {pregunta:"Sólido a líquido", opciones:["Fusión","Condensación","Evaporación","Sublimación"], correcta:0},
  {pregunta:"Líquido a gas", opciones:["Evaporación","Fusión","Sublimación","Condensación"], correcta:0},
  {pregunta:"Gas que respiramos", opciones:["Oxígeno","Nitrógeno","Dióxido de carbono","Helio"], correcta:0},
  {pregunta:"Ley de conservación de masa", opciones:["Lavoisier","Newton","Einstein","Dalton"], correcta:0},
  {pregunta:"Ion con carga positiva", opciones:["Catión","Anión","Electrón","Neutrón"], correcta:0},
  {pregunta:"Ion con carga negativa", opciones:["Anión","Catión","Protón","Neutrón"], correcta:0},
  {pregunta:"Número de Avogadro", opciones:["6.022×10²³","3.14","9.8","1.6×10⁻¹⁹"], correcta:0},
  {pregunta:"Mezcla homogénea", opciones:["Solución","Suspensión","Coloide","Mezcla heterogénea"], correcta:0},
  {pregunta:"Enlace químico en H2O", opciones:["Covalente","Iónico","Metálico","Intermolecular"], correcta:0},
  {pregunta:"Estado más abundante en la Tierra", opciones:["Gas","Líquido","Sólido","Plasma"], correcta:2}
]
};